name: Build library

on:
  push:
    tags:
      - 'v*'

env:
  LLAMACPP_VERSION: b4969
  CMAKE_COMMON_JOBS: '-DLLAMA_BUILD_COMMON=ON -DGGML_STATIC=ON -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF'
  CMAKE_COMMON_DIR: -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/libs -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{ github.workspace }}/build/libs

jobs:
  ################################ ArchChecker ################################

  archchecker_windows_build:
    name: Build ArchChecker Windows
    runs-on: windows-2019

    env:
        UPLOAD_NAME: windows-archchecker
        UPLOAD_PATH: archchecker/build/Release/archchecker.dll

    steps:
        @@checkout_recursive@@
        @@build_archchecker@@
        @@upload@@

################################ Windows ################################

  windows-build:
    runs-on: windows-2019

    env:
      CMAKE_COMMON: '-DBUILD_UNDREAMAI_BINARIES=ON -DGGML_NATIVE=OFF -DLLAMA_SERVER_SSL=ON'
      VULKAN_VERSION: 1.3.261.1
      PLATFORM: windows

    strategy:
      matrix:
        include:
          - build: 'noavx'
            defines: '-DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF'
          - build: 'avx2'
            defines: ''
          - build: 'avx'
            defines: '-DGGML_AVX2=OFF'
          - build: 'avx512'
            defines: '-DGGML_AVX512=ON'
          - build: 'cuda-cu12.4.0'
            defines: '-DGGML_CUDA=ON -DGGML_MINIMIZE_CODE_SIZE=ON -DGGML_NO_IQUANTS=ON'
            tinyBLAS: 'ON'
          - build: 'cuda-cu12.4.0-full'
            defines: '-DGGML_CUDA=ON'

    steps:
        @@checkout@@
        @@setup_llama_cpp@@
        @@add_licenses@@
        @@set_name@@

        @@setup_vulcan_windows@@
        @@setup_openssl_windows@@
        @@set_cuda_var@@
        @@setup_cuda_windows@@

        @@cpu-cores@@
        @@cmake_build@@

        @@move_files_windows@@
        @@copy_cuda_dlls@@
        @@pack_artifacts_windows@@
        @@upload@@

################################ Release ################################

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - archchecker_windows_build
      - windows-build
    steps:
        @@checkout@@
        @@download_artifacts@@
        @@merge_artifacts@@
        @@release@@
