name: Build library

on:
  push:
    tags:
      - 'v*'

env:
  LLAMACPP_VERSION: b5261
  CUDA: 12.2.0

jobs:
  linux-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - architecture: 'noavx'
            
    steps:
        @@setup_libs_linux@@

        @@setup_dirs@@
        @@checkout@@
        @@setup_llama_cpp@@
        @@add_licenses@@

        @@setup_vulkan_linux@@
        @@setup_cuda_linux@@
        @@link_cuda_linux@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build_unix@@

        @@pack_artifacts_unix@@
        @@upload@@
