name: Build library

on:
  push:
    tags:
      - 'v*'

env:
  CUDA: 12.4.1

jobs:
  ################################ Linux ################################

  linux-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - arch: linux_noavx
          - arch: linux_avx2
          - arch: linux_avx
          - arch: linux_avx512
          - arch: linux_vulkan
          - arch: linux_tinyblas
          - arch: linux_cublas
            
    steps:
        @@setup_libs_linux@@

        @@checkout@@
        @@add_licenses@@

        @@setup_vulkan_linux@@
        @@setup_cuda_linux@@
        @@link_cuda_linux@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build_linux@@

        @@pack_artifacts_unix@@
        @@upload_llamalib@@


  linux-hip-build:
    runs-on: ubuntu-22.04
    container: rocm/dev-ubuntu-22.04:5.5

    strategy:
      matrix:
        include:
          - arch: linux_hip

    steps:
        @@setup_libs_linux@@
        @@setup_hip_linux@@

        @@checkout@@
        @@add_licenses@@

        @@cpu-cores@@
        @@cmake_build@@

        @@pack_artifacts_unix@@
        @@upload_llamalib@@

################################ macOS ################################

  macOS-arm64-build:
    runs-on: macos-14

    strategy:
      matrix:
        include:
          - arch: macos_arm64_acc
          - arch: macos_arm64_no_acc

    steps:
        @@setup_libs_macos@@

        @@checkout@@
        @@add_licenses@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build_macos@@

        @@pack_artifacts_unix@@
        @@upload_llamalib@@

  macOS-x64-build:
    runs-on: macos-13

    strategy:
      matrix:
        include:
          - arch: macos_x64_acc
          - arch: macos_x64_no_acc

    steps:
        @@setup_libs_macos@@

        @@checkout@@
        @@add_licenses@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build_macos@@

        @@pack_artifacts_unix@@
        @@upload_llamalib@@


################################ Windows ################################

  windows-build:
    runs-on: windows-2022

    env:
      VULKAN_VERSION: 1.3.261.1
      PLATFORM: windows

    strategy:
      matrix:
        include:
          - arch: windows_noavx
          - arch: windows_avx2
          - arch: windows_avx
          - arch: windows_avx512
          - arch: windows_vulkan
          - arch: windows_tinyblas
          - arch: windows_cublas

    steps:
        @@checkout@@
        @@add_licenses@@

        @@setup_vulcan_windows@@
        @@setup_openssl_windows@@
        @@setup_cuda_windows@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build_windows@@

        @@copy_cuda_dlls@@
        @@pack_artifacts_windows@@
        @@upload_llamalib@@

  windows-hip-build:
    runs-on: windows-2022

    env:
      PLATFORM: windows
    
    strategy:
      matrix:
        include:
          - arch: windows_hip

    steps:
        @@checkout@@
        @@add_licenses@@

        @@setup_openssl_windows@@
        @@setup_hip_windows@@

        @@cpu-cores@@
        @@cmake_build_hip_windows@@

        @@pack_artifacts_windows@@
        @@upload_llamalib@@

################################ Android ################################

  android-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - arch: android_arm64
            ABI: arm64-v8a
          - arch: android_x64
            ABI: x86_64

    steps:
        @@setup_libs_linux@@

        @@checkout@@
        @@add_licenses@@

        @@cpu-cores@@
        @@build_openssl@@
        @@cmake_build_android@@

        @@pack_artifacts_unix@@
        @@upload_llamalib@@

################################ iOS ################################

  ios-build:
    runs-on: macos-14

    strategy:
      matrix:
        include:
          - arch: ios
            cmake_vars: '-DCMAKE_SYSTEM_NAME=iOS'
          - arch: visionos
            cmake_vars: '-DCMAKE_SYSTEM_NAME=visionOS'

    steps:
        @@setup_libs_macos@@

        @@checkout@@
        @@add_licenses@@

        @@cpu-cores@@
        @@build_openssl@@
        @@cmake_build@@
        @@link_libraries_ios@@

        @@pack_artifacts_ios@@
        @@upload_llamalib@@

################################ Release ################################

  create_release:
    name: Create Release
    runs-on: macos-14
    needs:
      - linux-build
      - linux-hip-build
      - macOS-arm64-build
      - macOS-x64-build
      - windows-build
      - windows-hip-build
      - android-build
      - ios-build
    steps:
        @@checkout@@
        @@set_release_prefix@@
        @@download_artifacts@@
        @@structure_artifacts@@
        @@create_release@@
        @@release@@
