name: Build library

on:
  push:
    tags:
      - 'v*'

env:
  CUDA: 12.4.1

jobs:
  ################################ Linux ################################

  linux-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - arch: linux-x64_noavx
          - arch: linux-x64_avx2
          - arch: linux-x64_avx
          - arch: linux-x64_avx512
          - arch: linux-x64_vulkan
          - arch: linux-x64_tinyblas
          - arch: linux-x64_cublas
            
    steps:
        @@setup_libs_linux@@
        @@checkout@@
        @@preparation@@
        @@setup_vulkan_linux@@
        @@setup_cuda_linux@@
        @@link_cuda_linux@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build@@

        @@pack_artifacts@@
        @@upload_llamalib@@

################################ macOS ################################

  osx-arm64-build:
    runs-on: macos-15

    strategy:
      matrix:
        include:
          - arch: osx-arm64_acc
          - arch: osx-arm64_no-acc

    steps:
        @@setup_libs_macos@@
        @@checkout@@
        @@preparation@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build@@

        @@pack_artifacts@@
        @@upload_llamalib@@

  osx-x64-build:
    runs-on: macos-15-intel

    strategy:
      matrix:
        include:
          - arch: osx-x64_acc
          - arch: osx-x64_no-acc

    steps:
        @@setup_libs_macos@@
        @@checkout@@
        @@preparation@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build@@

        @@pack_artifacts@@
        @@upload_llamalib@@

  osx-universal-build:
    runs-on: macos-15
    needs:
      - osx-arm64-build
      - osx-x64-build

    strategy:
      matrix:
        include:
          - arch: osx-universal

    steps:
        @@download_macos_artifacts@@
        @@combine_macos_libraries@@
        @@upload_llamalib@@

################################ Windows ################################

  windows-build:
    runs-on: windows-2022

    env:
      VULKAN_VERSION: 1.4.328.1
      PLATFORM: windows

    strategy:
      matrix:
        include:
          - arch: win-x64_noavx
          - arch: win-x64_avx2
          - arch: win-x64_avx
          - arch: win-x64_avx512
          - arch: win-x64_vulkan
          - arch: win-x64_tinyblas
          - arch: win-x64_cublas

    steps:
        @@checkout@@
        @@preparation@@
        @@setup_vulcan_windows@@
        @@setup_cuda_windows@@

        @@cpu-cores@@
        @@cmake_build@@
        @@test_build@@

        @@copy_cuda_dlls@@
        @@pack_artifacts@@
        @@upload_llamalib@@

################################ Android ################################

  android-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - arch: android-arm64
            ABI: arm64-v8a
          - arch: android-x64
            ABI: x86_64

    steps:
        @@setup_libs_linux@@
        @@checkout@@
        @@preparation@@

        @@cpu-cores@@
        @@build_openssl@@
        @@cmake_build_android@@

        @@pack_artifacts@@
        @@upload_llamalib@@

################################ iOS ################################

  ios-build:
    runs-on: macos-14

    strategy:
      matrix:
        include:
          - arch: ios-arm64
            cmake_vars: '-DCMAKE_SYSTEM_NAME=iOS'
          - arch: visionos-arm64
            cmake_vars: '-DCMAKE_SYSTEM_NAME=visionOS'

    steps:
        @@setup_libs_macos@@
        @@checkout@@
        @@preparation@@

        @@cpu-cores@@
        @@cmake_build@@
        @@link_libraries_ios@@

        @@pack_artifacts@@
        @@upload_llamalib@@

################################ Release ################################

  create_release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs:
      - linux-build
      - osx-arm64-build
      - osx-x64-build
      - osx-universal-build
      - windows-build
      - android-build
      - ios-build
    steps:
        @@checkout@@
        @@preparation@@
        @@set_release_version@@
        @@download_artifacts@@
        @@create_release@@
        @@test_cmake@@
        @@pack_nuget@@
        @@clean_up_release@@
        @@test_nuget@@
        @@release@@
