name: Build iOS .ipa with Xcode

on:
  push:

jobs:
  build:
    runs-on: macos-latest  # Use macOS for iOS builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install gdown
        run: |
          python -m pip install --upgrade pip
          pip install gdown

      - name: Download Google Drive folder
        run: |
          gdown --folder "https://drive.google.com/drive/folders/1t5S4chMSoPFZTxSzoTUGN5PB2ud15I67?usp=sharing" -O ios-app

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app  # Adjust for the Xcode version you're using

      - name: Build the .ipa file
        run: |
          cd ios-app
          xcodebuild clean build -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -configuration Release -destination 'platform=iOS,arch=arm64' -archivePath $PWD/build/Unity-iPhone.xcarchive clean archive

      - name: Export the .ipa file
        run: |
          cd ios-app
          xcodebuild -exportArchive -archivePath $PWD/build/Unity-iPhone.xcarchive -exportPath $PWD/build/Unity-iPhone.ipa -exportOptionsPlist ExportOptions.plist
          
      - name: Upload .ipa as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS-ipa
          path: $PWD/build/Unity-iPhone.ipa
          