name: Build iOS .ipa with Xcode

on:
  push:

jobs:
  build:
    runs-on: macos-latest  # Use macOS for iOS builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install gdown
        run: |
          python -m pip install --upgrade pip
          pip install gdown

      - name: Download Google Drive folder
        run: |
          gdown "https://drive.google.com/uc?export=download&id=1rxP1tweVqbG7n-Yr8-9o1UEf_VCbM1R2" -O ios.zip

      - name: Extract the ZIP file
        run: |
          unzip ios.zip

      - name: Select Xcode
        run: |
          ls /Applications
          sudo xcode-select -switch /Applications/Xcode.app

      - name: Decode and Install Code Signing Certificate
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          echo "$P12_BASE64" | base64 --decode > signing_certificate.p12
          security import signing_certificate.p12 -P "$CERT_PASSWORD" -A
          rm signing_certificate.p12

      - name: Build the .ipa file
        run: |
          cd ios
          xcodebuild clean build -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -configuration Release -destination 'platform=iOS,arch=arm64' -archivePath $PWD/build/Unity-iPhone.xcarchive clean archive

      - name: Export the .ipa file
        run: |
          cd ios
          xcodebuild -exportArchive -archivePath $PWD/build/Unity-iPhone.xcarchive -exportPath $PWD/build/Unity-iPhone.ipa -exportOptionsPlist ExportOptions.plist
          
      - name: Upload .ipa as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS-ipa
          path: $PWD/build/Unity-iPhone.ipa
          