name: Build iOS .ipa with Xcode

on:
  push:

jobs:
  build:
    runs-on: macos-latest  # Use macOS for iOS builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install gdown
        run: |
          python -m pip install --upgrade pip
          pip install gdown

      - name: Download Google Drive folder
        run: |
          gdown "https://drive.google.com/uc?export=download&id=1rxP1tweVqbG7n-Yr8-9o1UEf_VCbM1R2" -O ios.zip

      - name: Extract the ZIP file
        run: |
          unzip ios.zip

      - name: Select Xcode
        run: |
          ls /Applications
          sudo xcode-select -switch /Applications/Xcode.app

      - name: Decode and Install Code Signing Certificate
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          echo "$P12_BASE64" | base64 --decode > signing_certificate.p12
          security import signing_certificate.p12 -P "$CERT_PASSWORD" -A
          rm signing_certificate.p12

      - name: Build the .ipa file
        run: |
          cd ios
          xcodebuild clean archive \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath $PWD/build/Unity-iPhone.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=${{ secrets.TEAM_ID }}

      - name: Build the .ipa file
        run: |
          mkdir Payload
          mv ios/build/Unity-iPhone.xcarchive/Products/Applications/*app Payload
          zip -r test.iap Payload

      - name: Upload .ipa as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test.iap
          path: test.iap
