name: Build library

on:
  push:
    tags:
      - 'v*'

env:
  LLAMACPP_VERSION: b4969
  CMAKE_COMMON_JOBS: '-DLLAMA_BUILD_COMMON=ON -DGGML_STATIC=ON -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF'
  CMAKE_COMMON_DIR: -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/libs -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{ github.workspace }}/build/libs

jobs:
  ################################ ArchChecker ################################

  archchecker_windows_build:
    name: Build ArchChecker Windows
    runs-on: windows-2019

    env:
        UPLOAD_NAME: windows-archchecker
        UPLOAD_PATH: archchecker/build/Release/archchecker.dll

    steps:
        - id: checkout_recursive
          name: Clone
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - id: build_archchecker
          name: Build
          run: |
            mkdir archchecker/build
            cd archchecker/build
            cmake ..
            cmake --build . --config Release -j $(nproc)

        - id: upload
          name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.UPLOAD_NAME }}
            path: ${{ env.UPLOAD_PATH }}


################################ Windows ################################

  windows-build:
    runs-on: windows-2019

    env:
      CMAKE_COMMON: '-DBUILD_UNDREAMAI_BINARIES=ON -DGGML_NATIVE=OFF -DLLAMA_SERVER_SSL=ON'
      VULKAN_VERSION: 1.3.261.1
      PLATFORM: windows

    strategy:
      matrix:
        include:
          - build: 'noavx'
            defines: '-DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF'
          - build: 'avx2'
            defines: ''
          - build: 'avx'
            defines: '-DGGML_AVX2=OFF'
          - build: 'avx512'
            defines: '-DGGML_AVX512=ON'
          - build: 'cuda-cu12.4.0'
            defines: '-DGGML_CUDA=ON -DGGML_MINIMIZE_CODE_SIZE=ON -DGGML_NO_IQUANTS=ON'
            tinyBLAS: 'ON'
          - build: 'cuda-cu12.4.0-full'
            defines: '-DGGML_CUDA=ON'

    steps:
        - id: checkout
          name: Clone
          uses: actions/checkout@v4

        - id: setup_llama_cpp
          name: Setup llama.cpp
          run: |
            git clone https://github.com/ggerganov/llama.cpp llama.cpp
            cd llama.cpp
            git checkout ${{ env.LLAMACPP_VERSION }}
        
            git apply ../fixes/llama.cpp.patch
            if [ -f ../fixes/${{ env.LLAMACPP_VERSION }}.sh ];then
              . ../fixes/${{ env.LLAMACPP_VERSION }}.sh
            fi
            if [[ "${{ matrix.tinyBLAS }}" != "" ]]; then
              echo "tinyBLAS"
              mv ggml/src/ggml-cuda/CMakeLists.txt CMakeLists.txt.ggml-cuda
              rm -r ggml/src/ggml-cuda
              cp -R ../tinyBLAS ggml/src/ggml-cuda
              mv CMakeLists.txt.ggml-cuda ggml/src/ggml-cuda/CMakeLists.txt
            fi
        
            for f in examples/server/public/*;do
                cmake -DINPUT="$f" -DOUTPUT="$(echo "$f" | sed -e 's:public/::g').hpp" -P "scripts/xxd.cmake"
            done
          shell: bash

        - id: add_licenses
          name: Add licenses
          run: |
            mkdir -p build/licenses build/libs
            cp llama.cpp/LICENSE build/licenses/llama.cpp.LICENSE.txt
            if [[ "${{ matrix.tinyBLAS }}" != "" ]]; then
              curl -o build/licenses/llamafile.LICENSE.txt -L https://raw.githubusercontent.com/Mozilla-Ocho/llamafile/main/LICENSE
            fi
          shell: bash

        - id: set_name
          name: Set name
          run: |
            LIBRARY_SUFFIX="${{ env.PLATFORM }}"
            if [ "${{ matrix.build }}" != "" ];then LIBRARY_SUFFIX="$LIBRARY_SUFFIX-${{ matrix.build }}"; fi
            NAME=undreamai-${{ github.ref_name }}-llamacpp-$LIBRARY_SUFFIX.zip
            echo "LIBRARY_SUFFIX=$LIBRARY_SUFFIX" >> $GITHUB_ENV
            echo "UPLOAD_NAME=$NAME" >> $GITHUB_ENV
            echo "UPLOAD_PATH=$NAME" >> $GITHUB_ENV
          shell: bash


        - id: setup_vulcan_windows
          if: matrix.build == 'vulkan'
          name: Install Vulkan SDK
          run: |
            curl.exe -o $env:RUNNER_TEMP/VulkanSDK-Installer.exe -L "https://sdk.lunarg.com/sdk/download/${env:VULKAN_VERSION}/windows/VulkanSDK-${env:VULKAN_VERSION}-Installer.exe"
            & "$env:RUNNER_TEMP\VulkanSDK-Installer.exe" --accept-licenses --default-answer --confirm-command install
            Add-Content $env:GITHUB_ENV "VULKAN_SDK=C:\VulkanSDK\${env:VULKAN_VERSION}"
            Add-Content $env:GITHUB_PATH "C:\VulkanSDK\${env:VULKAN_VERSION}\bin"
            curl.exe -o $env:RUNNER_TEMP/VulkanRT-Components.zip -L "https://sdk.lunarg.com/sdk/download/1.3.283.0/windows/VulkanRT-1.3.283.0-Components.zip"
            7z x "-o${env:RUNNER_TEMP}" $env:RUNNER_TEMP/VulkanRT-Components.zip
            mkdir .\build\libs\Release
            cp ${env:RUNNER_TEMP}/VulkanRT*\x64\vulkan-1.dll .\build\libs\Release

        - id: setup_openssl_windows
          name: Install OpenSSL
          run: |
            choco install openssl --no-progress
            $OPENSSL_ROOT_DIR = 'C:\Program Files\OpenSSL'
            Copy-Item $OPENSSL_ROOT_DIR\lib\VC\x64\MD\*.lib $OPENSSL_ROOT_DIR\lib\
            Copy-Item $OPENSSL_ROOT_DIR\lib\libcrypto_static.lib $OPENSSL_ROOT_DIR\lib\libcrypto.a
            Copy-Item $OPENSSL_ROOT_DIR\lib\libssl_static.lib $OPENSSL_ROOT_DIR\lib\libssl.a
            Add-Content $env:GITHUB_ENV "OPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR"

        - id: set_cuda_var
          if: startsWith(matrix.build, 'cuda')
          name: Set CUDA variable
          run: |
            echo "CUDA=$(echo "${{ matrix.build }}" | cut -d '-' -f2 | cut -c 3- )" >> $GITHUB_ENV
            echo "LD_LIBRARY_PATH=''" >> $GITHUB_ENV
          shell: bash

        - id: setup_cuda_windows
          if: startsWith(matrix.build, 'cuda')
          uses: Jimver/cuda-toolkit@v0.2.15
          with:
            cuda: ${{ env.CUDA }}
            method: network
            sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'


        - id: cpu-cores
          name: Get number of CPU cores
          uses: SimenB/github-actions-cpu-cores@v2

        - id: cmake_build
          name: Build
          run: |
            cd build
            cmake .. -DLIBRARY_SUFFIX="${{ env.LIBRARY_SUFFIX }}" ${{ matrix.defines }} ${{ env.CMAKE_COMMON }} ${{ env.CMAKE_COMMON_JOBS }} ${{ env.CMAKE_COMMON_DIR }}
            cmake --build . --config Release -j ${{ steps.cpu-cores.outputs.count }}


        - id: move_files_windows
          if: startsWith(matrix.build, 'hip')
          name: Move files to Release folder
          run: |
            mkdir build/Release
            mkdir build/libs/Release
            move build/libs/*exe build/libs/Release
            move build/libs/*dll build/libs/Release
            move build/libs/*exp build/libs/Release
            move build/libs/*lib build/libs/Release

        - id: copy_cuda_dlls
          if: ${{ startsWith(matrix.build, 'cuda') && matrix.tinyBLAS == '' }}
          name: Copy Cuda DLLs
          run: |
            mv "${{ env.CUDA_PATH }}"/bin/cudart64_*.dll build/libs/Release
            mv "${{ env.CUDA_PATH }}"/bin/cublas64_*.dll build/libs/Release
            mv "${{ env.CUDA_PATH }}"/bin/cublasLt64_*.dll build/libs/Release
          shell: bash

        - id: pack_artifacts_windows
          name: Pack artifacts
          run: |
            ls -R build
            del build/libs/Release/undreamai_test.*
            mkdir artifacts
            move .\build\licenses\* .\artifacts\
            move .\build\Release\* .\artifacts\
            move .\build\libs\Release\*dll .\artifacts\
            $serverPath = ".\build\libs\Release\undreamai_server.exe"
            if (Test-Path $serverPath) {
                move $serverPath -Destination ".\artifacts\"
            }
            cd artifacts
            7z a ../${{ env.UPLOAD_NAME }} *

        - id: upload
          name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.UPLOAD_NAME }}
            path: ${{ env.UPLOAD_PATH }}


################################ Release ################################

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - archchecker_windows_build
      - windows-build
    steps:
        - id: checkout
          name: Clone
          uses: actions/checkout@v4

        - id: download_artifacts
          name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts

        - id: merge_artifacts
          name: Merge artifacts
          run: |
            cd artifacts
            ls -R
            PREFIX=undreamai-${{ github.ref_name }}-llamacpp
        
            for d in `ls | grep $PREFIX`;do
              cd $d; unzip $d; rm $d; cd ..;
              new_name=`echo $d | sed -e "s:$PREFIX-::g" | sed -e 's:.zip::g'`
              mv $d $new_name;
              echo $new_name >> bundle
            done
        
            servers=`find . -name undreamai_server*`
            if [ "$servers" != "" ];then
              zip -r undreamai-${{ github.ref_name }}-server.zip $servers
              rm $servers
            fi
        
            zip -r $PREFIX.zip `cat bundle | grep -v full` linux-archchecker windows-archchecker
            zip -r $PREFIX-full.zip `cat bundle | grep full`

        - id: release
          name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: artifacts/*.zip
            name: Release ${{ github.ref_name }}

