name: Build library

on:
  push:

env:
  LLAMACPP_VERSION: b2989
  LLAMAFILE_VERSION: 0.8.6
  CMAKE_COMMON_JOBS: '-DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DBUILD_UNDREAMAI_SERVER=ON'
  CMAKE_COMMON_DIR: -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/libs -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{ github.workspace }}/build/libs

jobs:
  macOS-arm64-build:
    runs-on: macos-14

    strategy:
      matrix:
        include:
          - build: 'no_acc'
            defines: '-DLLAMA_ACCELERATE=OFF'
          - build: 'acc'
            defines: ''

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Clone llama.cpp
        run: |
          git clone https://github.com/ggerganov/llama.cpp llama.cpp
          cd llama.cpp
          git checkout ${{ env.LLAMACPP_VERSION }}
          sed -i.bak 's:utils.hpp:utils_callback.hpp:g' examples/server/server.cpp
          sed -i.bak 's:main(int argc:main_server(int argc:g' examples/server/server.cpp
          cd ..
          mkdir -p build/licenses build/libs
          cp llama.cpp/LICENSE build/licenses/llama.cpp.LICENSE.txt

      - name: Create missing files
        run: |
          cd llama.cpp
          for f in examples/server/public/*;do
            cmake -DINPUT=$f -DOUTPUT=`echo $f|sed -e 's:public/::g'`.hpp -P scripts/xxd.cmake
          done
  
      - name: Dependencies
        id: depends
        continue-on-error: true
        run: |
          brew update

      - name: Build
        id: cmake_build
        run: |
          sed -i.bak "s:LIBRARY undreamai:LIBRARY undreamai_macos-arm64-${{ matrix.build }}:g" CMakeLists.txt
          cd build
          cmake -DLLAMA_FATAL_WARNINGS=ON -DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_CURL=ON ${{ matrix.defines }} ${{ env.CMAKE_COMMON_JOBS }} ${{ env.CMAKE_COMMON_DIR }} ..
          cmake --build . --config Release -j $(sysctl -n hw.logicalcpu)

      - name: Pack artifacts
        id: pack_artifacts
        run: |
          rm build/libs/undreamai_test
          ls -R build
          zip -j undreamai-test-llamacpp-macos-arm64-${{ matrix.build }}.zip build/licenses/* build/libs/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: undreamai-test-llamacpp-macos-arm64-${{ matrix.build }}.zip
          path: undreamai-test-llamacpp-macos-arm64-${{ matrix.build }}.zip

      - name: Test
        run: |
          cd build/libs
          curl -L -o model.gguf https://huggingface.co/afrideva/smol_llama-220M-openhermes-GGUF/resolve/main/smol_llama-220m-openhermes.q4_k_m.gguf?download=true
          ./undreamai_test -m model.gguf -np 1 --log-disable
          rm model.gguf

  macOS-x64-build:
    runs-on: macos-12

    strategy:
      matrix:
        include:
          - build: 'no_acc'
            defines: '-DLLAMA_ACCELERATE=OFF'
          - build: 'acc'
            defines: ''

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Clone llama.cpp
        run: |
          git clone https://github.com/ggerganov/llama.cpp llama.cpp
          cd llama.cpp
          git checkout ${{ env.LLAMACPP_VERSION }}
          sed -i.bak 's:utils.hpp:utils_callback.hpp:g' examples/server/server.cpp
          sed -i.bak 's:main(int argc:main_server(int argc:g' examples/server/server.cpp
          cd ..
          mkdir -p build/licenses build/libs
          cp llama.cpp/LICENSE build/licenses/llama.cpp.LICENSE.txt

      - name: Create missing files
        run: |
          cd llama.cpp
          for f in examples/server/public/*;do
            cmake -DINPUT=$f -DOUTPUT=`echo $f|sed -e 's:public/::g'`.hpp -P scripts/xxd.cmake
          done
  
      - name: Dependencies
        id: depends
        continue-on-error: true
        run: |
          brew update

      - name: Build
        id: cmake_build
        run: |
          sed -i.bak "s:LIBRARY undreamai:LIBRARY undreamai_macos-x64-${{ matrix.build }}:g" CMakeLists.txt
          cd build
          cmake -DLLAMA_FATAL_WARNINGS=ON -DLLAMA_METAL=OFF -DLLAMA_CURL=ON ${{ matrix.defines }} ${{ env.CMAKE_COMMON_JOBS }} ${{ env.CMAKE_COMMON_DIR }} ..
          cmake --build . --config Release -j $(sysctl -n hw.logicalcpu)

      - name: Test
        id: test
        run: |
          cd build/libs
          curl -L -o model.gguf https://huggingface.co/afrideva/smol_llama-220M-openhermes-GGUF/resolve/main/smol_llama-220m-openhermes.q4_k_m.gguf?download=true
          ./undreamai_test -m model.gguf -np 1 --log-disable
          rm model.gguf

      - name: Pack artifacts
        id: pack_artifacts
        run: |
          rm build/libs/undreamai_test
          ls -R build
          zip -j undreamai-test-llamacpp-macos-x64-${{ matrix.build }}.zip build/licenses/* build/libs/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: undreamai-test-llamacpp-macos-x64-${{ matrix.build }}.zip
          path: undreamai-test-llamacpp-macos-x64-${{ matrix.build }}.zip

      - name: Test
        run: |
          cd build/libs
          curl -L -o model.gguf https://huggingface.co/afrideva/smol_llama-220M-openhermes-GGUF/resolve/main/smol_llama-220m-openhermes.q4_k_m.gguf?download=true
          ./undreamai_test -m model.gguf -np 1 --log-disable
          rm model.gguf